# Configuration for librarian-puppet. For example:
# 
forge "http://forge.puppetlabs.com"
# 
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "puppetlabs/mysql"
mod "puppetlabs/vcsrepo"

mod "puppetlabs/java", :git => "https://github.com/puppetlabs/puppetlabs-java"
mod "hadoop", :path => "/vagrant/puppet/local-modules/hadoop"
mod "demo_build", :path => "/vagrant/puppet/local-modules/demo_build"
